#pragma once

#include <string>
#include <vector>
#include "weapon.h"

struct Occupation
{
  std::string name;
  Weapon weapon;
  std::vector<std::string> gear;
};

Occupation default_occupation={"Peasant", default_weapon, {}};

std::vector <Occupation> occupation_table={
  {"Advocate", default_weapon, {"book of legal formalities", "glasses", "quill", "ink", "1d4 sheets of paper", "stately clothes"}},
  {"Apothecary", default_weapon, {"book of recipes", "healer's kit", "pint of oil", "flask of acid", "common clothes"}},
  {"Artist", default_weapon, {"paint brushes", "palette", "professional paints", "funny-looking hat", "half finished painting", "common clothes"}},
  {"Astronomer", default_weapon, {"spyglass", "robe", "book of planetary charts", "common clothes"}},
  {"Atilliator", light_crossbow, {"light crossbow", "1dbolts", "sinew", "common clothes"}},
  {"Bailiff", default_weapon, {"seal of the local noble", "accounting book", "quill", "1d4 sheets of paper", "bottle of ink", "stately clothes"}},
  {"Baker", {"Rolling Pin", STR, 4}, {"rolling pin", "sack of flour", "1d4 apples", "common clothes"}},
  {"Barber", {"Sharp Razor", STR, 4}, {"sharp razor", "apron", "comb", "common clothes"}},
  {"Basket Weaver", default_weapon, {"heavy basket", "1d4 pounds of flat reeds", "basket making tools", "full waterskin", "common clothes"}},
  {"Beggar", {"Dull Knife", STR, 4}, {"dull knife", "ragged clothes with a fake pocket", "begging dish"}},
  {"Bellmaker", {"Small Hammer", STR, 4}, {"1d8 sleigh bells", "small hammer", "1d4 bell molds", "common clothes"}},
  {"Blacksmith", {"Smithing Hammer", STR, 4}, {"smithing hammer", "scraps of metal", "leather apron", "common clothes"}},
  {"Bookbinder", default_weapon, {"bottle of glue", "1d4 well-made books", "glasses", "common clothes"}},
  {"Bowyer", shortbow, {"shortbow", "sharp knife", "1darrows", "quiver", "common clothes"}},
  {"Brewer", default_weapon, {"sturdy pot", "sack of malted barley", "small keg of beer", "common clothes"}},
  {"Bricklayer", {"Brick", STR, 4}, {"level", "1d4 bricks", "recipe for mortar", "trowel", "common clothes"}},
  {"Butcher", {"Cleaver", STR, 4}, {"cleaver", "blood stained apron", "small ration of salted meat", "common clothes"}},
  {"Carpenter", {"Work Mallet", STR, 4}, {"work mallet", "handheld auger", "1d8 nails", "common clothes"}},
  {"Cartwright", {"Dull Knife", STR, 4}, {"1d4 wagon wheel spokes", "dull knife", "notes for your current project", "common clothes"}},
  {"Catchpole", {"Knife", STR, 4}, {"knife", "cloak", "warrant for the arrest of a debtor", "boots", "common clothes"}},
  {"Chandler", default_weapon, {"1d20 candles", "1d4 bars of soap", "1d10 pounds of wax", "small box of matches", "common clothes"}},
  {"Charcoaler", {"Shovel", STR, 4}, {"shovel", "1d4 pounds of charcoal", "soot stained clothes"}},
  {"Clerk", default_weapon, {"book of accounts", "1d4 pieces of paper", "quill", "bottle of ink", "stately clothes"}},
  {"Cobbler", {"Tack Hammer", STR, 4}, {"tack hammer", "box of nails", "1d4 pairs of new boots", "common clothes"}},
  {"Colporteur", default_weapon, {"1d20 pamphlets", "1d4 ordinary books", "1d4 religious texts", "common clothes"}},
  {"Constable", club, {"club", "chain of authority", "official hat", "uniform", "iron cufflinks with a key"}},
  {"Cook", {"Metal Pan", STR, 4}, {"metal pan", "warm meal in a basket", "chef's knife", "white uniform"}},
  {"Cooper", default_weapon, {"stout piece of wood", "two empty barrels", "barrel shaping tools", "common clothes"}},
  {"Cowherd", {"Walking Stick", STR, 4}, {"walking stick", "1d8 turnips", "1d4 cows", "common clothes"}},
  {"Criminal", {"Sharp Knife", STR, 4}, {"sharp knife", "small stolen item (player's choice)", "ragged clothes"}},
  {"Ditcher", {"Shovel", STR, 4}, {"shovel", "that day's lunch", "common clothes"}},
  {"Dyer", default_weapon, {"1d4 dyes", "1d4 sheets of brightly colored cloth", "well dyed clothes", "boots"}},
  {"Eggler", default_weapon, {"2d20 eggs", "2 chickens that follow you", "common clothes", "boots"}},
  {"Entertainer", default_weapon, {"well tuned lute", "brightly colored clothes", "a set of makeup", "3 juggling balls"}},
  {"Falconer", default_weapon, {"well trained falcon", "heavy gauntlet", "falcon hood", "common clothes", "boots"}},
  {"Famulus", default_weapon, {"empty book of spells", "historical guide to the area", "1d4 sheaves of blank paper", "common clothes"}},
  {"Farmer", {"Pitchfork", STR, 4}, {"pitchfork", "straw hat", "small sack of grain", "common clothes"}},
  {"Farrier", {"Tack Hammer", STR, 4}, {"tack hammer", "8 horseshoes", "box of nails", "common clothes"}},
  {"Fisher", default_weapon, {"pole and line", "dried fish meat", "small cup of worms", "common clothes", "waterproof boots"}},
  {"Fletcher", shortbow, {"sharp knife", "shortbow", "2d20 arrows", "quiver", "common clothes"}},
  {"Forester", shortbow, {"hatchet", "shortbow", "1d4 arrows", "compass", "muddy boots", "common clothes"}},
  {"Fortune Teller", default_weapon, {"tarot deck", "small tarot deck guide book", "scuffed \"crystal\" ball", "flowing robes", "pointy hat"}},
  {"Gambler", default_weapon, {"2d20 sp", "pair of loaded dice", "normal dice", "debt of 1d20 gp", "common clothes"}},
  {"Gardener", {"Spade", STR, 4}, {"spade", "1d4 carrots", "1d6 potatoes", "packet of seeds", "common clothes"}},
  {"Glassworker", {"Steel Blowpipe", STR, 4}, {"steel blowpipe", "1d4 glasses", "small bucket of pure sand", "common clothes"}},
  {"Glover", {"Sharp Knife", STR, 4}, {"1d4 pairs of well stitched gloves", "sharp knife", "needle and thread", "1d6 skins", "common clothes"}},
  {"Hat Maker", default_weapon, {"needle and thread", "1d4 fancy hats", "1d6 beaver pelts", "mannequin head", "common clothes"}},
  {"Hayward", {"Large Belt Knife", STR, 4}, {"loud horn", "map of the local area", "large belt knife", "woolen clothes", "boots"}},
  {"Herbalist", {"Small Knife", STR, 4}, {"1d4 packets of dried herbs", "1d4 packets of seeds", "small knife", "book on herbs", "common clothes"}},
  {"Hound Trainer", default_weapon, {"1d4 well trained dogs", "1 bag of dog snacks", "2d4 dog food rations", "common clothes", "boots"}},
  {"Innkeeper", {"Axe Handle", STR, 4}, {"axe handle", "waterskin filled with wine", "apron", "common clothes"}},
  {"Janitor", {"Staff", STR, 4}, {"staff", "list of approved guests", "uniform"}},
  {"Jeweler", default_weapon, {"1d4 jewelry molds", "metal tongs", "scrap metals", "common clothes"}},
  {"Linkman", default_weapon, {"1d4 torches", "knapsack", "pint of oil", "common clothes"}},
  {"Locksmith", default_weapon, {"thieves’ tools", "set of master keys", "well made lock and key", "common clothes"}},
  {"Mason", {"Masonry Hammer", STR, 4}, {"masonry hammer", "level", "stone carving tools", "symbol to a secret society", "common clothes"}},
  {"Miller", default_weapon, {"hand quern", "1d4 sacks of flour", "common clothes"}},
  {"Mime", default_weapon, {"white face paint", "black performance clothes", "fun hat", "common clothes"}},
  {"Miner", {"Pickaxe", STR, 4}, {"pickaxe", "lantern", "pint of oil", "50 feet of rope", "common clothes"}},
  {"Noble", {"Blunt Epee", STR, 4}, {"blunt epee", "deed to a large farm", "2d10+10 gold pieces", "silk clothes", "high end boots"}},
  {"Ostler", default_weapon, {"riding crop", "brush", "small bag of horse feed", "common clothes"}},
  {"Outfitter", {"Heavy Belt Knife", STR, 4}, {"heavy belt knife", "backpack", "flint and steel", "fishing pole", "well worn boots", "common clothes"}},
  {"Page", {"Wooden Practice Sword", STR, 4}, {"wooden practice sword", "clothes brush", "a forgotten message", "livery", "scuffed boots"}},
  {"Pastry Chef", {"Rolling Pin", STR, 4}, {"1d4 pastries", "recipe for a \"superior\" dough", "apron", "rolling pin", "common clothes"}},
  {"Peddler", default_weapon, {"local area map", "sack of 1d10 trinkets and 1d20 baubles", "common clothes", "comfortable boots"}},
  {"Philosopher", default_weapon, {"tome of logic", "sheaf of notes", "quill", "ink bottle", "common clothes with ink stained sleeves"}},
  {"Physician", default_weapon, {"healer's kit", "healing herbs", "bandages", "common clothes"}},
  {"Pie Seller", {"Rolling Pin", STR, 4}, {"basket containing 1d4 fruit pies", "apron", "rolling pin", "common clothes"}},
  {"Plumer", default_weapon, {"sack of goose down", "fine pillow", "1d4 rare feathers", "common clothes"}},
  {"Poisoner", default_weapon, {"1d4 vials of basic poison", "treatise on poison", "cloak", "common clothes"}},
  {"Potter", default_weapon, {"1d4 pounds of clay", "potter’s wheel", "1d6 small clay jars", "common clothes"}},
  {"Priest", default_weapon, {"holy symbol", "healer's kit", "incense", "vestments", "small bottle of wine", "habit"}},
  {"Ratcatcher", club, {"club", "1d8 dead rats", "rat bait", "common clothes", "coat made out of clean rat skins"}},
  {"Roofer", {"Tack Hammer", STR, 4}, {"tack hammer", "1d4 bunches of thatch", "box of nails", "common clothes"}},
  {"Rope Maker", {"Sharp Knife", STR, 4}, {"sharp knife", "two 50 ft lengths of rope", "common clothes"}},
  {"Sage", default_weapon, {"book of lore", "quill", "ink", "few sheets of paper", "scroll of magic missile", "common clothes"}},
  {"Salter", {"Sharp Knife", STR, 4}, {"sharp knife", "1 pound of salted meat", "1d10 pounds of salt", "common clothes"}},
  {"Scribe", default_weapon, {"1d20 pages of paper", "half copied book", "quill", "1d4 colored inks", "common clothes"}},
  {"Scullion", {"Broom", STR, 4}, {"apron", "well worn brush", "half a loaf of bread", "broom", "common clothes"}},
  {"Servant", {"Dull Knife", STR, 4}, {"dull knife", "mark of indentured servitude", "common clothes"}},
  {"Spice Merchant", default_weapon, {"1d10 exotic spices", "small amount of cinnamon", "1d8 gp", "silk clothes", "shiny boots"}},
  {"Squire", longsword, {"longsword", "book on chivalry", "fine clothes", "polished boots"}},
  {"Stevedore", {"Heavy Belt Knife", STR, 4}, {"thick belt", "heavy belt knife", "warm clothes", "heavy boots"}},
  {"Steward", default_weapon, {"livery", "chain of office", "book of the estate’s accounts", "velvet clothes"}},
  {"Swineherd", {"Crook", STR, 4}, {"crook", "1d8 turnips", "1d4 pigs", "common clothes"}},
  {"Tailor", default_weapon, {"needle and thread", "scraps of cloth", "well sewn vest", "common clothes"}},
  {"Tanner", {"Belt Knife", STR, 4}, {"belt knife", "1d6 animal skins", "thick gloves", "common clothes"}},
  {"Teamster", default_weapon, {"crop", "brush", "blanket", "small bag of horse feed", "common clothes"}},
  {"Timberwright", hand_axe, {"hand axe", "several small pieces of wood", "comfortable boots", "common clothes", "cloak"}},
  {"Tinker", {"Sharp Knife", STR, 4}, {"sharp knife", "sack full of 1d20 small trinkets", "small tools", "colorful clothes"}},
  {"Torturer", default_weapon, {"bag of \"special tools\"", "signed confession", "cloak", "common clothes"}},
  {"Town Crier", default_weapon, {"hand held bell", "fancy hat", "buckled shoes", "lantern", "common clothes"}},
  {"Veterinarian", default_weapon, {"book of animal diseases", "1d4 packs of herbs", "small bag of horse feed", "common clothes"}},
  {"Vintner", default_weapon, {"1d6 bottles of cheap wine", "1d4 bottles of rare wine", "common clothes", "boots"}},
  {"Watchman", spear, {"spear", "steel helmet", "lantern", "well-made boots", "uniform", "cloak"}},
  {"Weaver", default_weapon, {"1d6 pounds thread", "loom tools", "hand loom", "a finely woven cape", "common clothes"}},
  {"Witch's Apprentice", {"Knife", STR, 4}, {"knife", "scroll of burning hands", "jar of \"newt eyes\"", "common clothes", "cloak"}},
  {"Woodcrafter", hand_axe, {"hand axe", "small knife", "small carved wooden item", "common clothes"}},
  {"Yeoman", shortsword, {"longbow", "shortsword", "1d10 arrows", "title to a small farm", "cloak", "common clothes", "boots"}},
};
