#pragma once

#include <vector>
#include <string>

std::vector<std::string> quirks_phys={
"A mark of Fey ancestry",
"Almond-shaped eyes",
"Amputee",
"Authentic limp",
"Bald",
"Beady eyes",
"Beard",
"Beautiful",
"Beer gut",
"Big ears",
"Broad-shouldered",
"Bushy mustache",
"Button nose",
"Chapped lips",
"Cleft chin",
"Club foot",
"Completely unremarkable",
"Constantly dirty",
"Cross-eyed",
"Curly hair",
"Curvaceous",
"Differently colored eyes",
"Disarmingly adorable",
"Eye patch",
"Facial scar",
"Facial tick",
"Fair skin",
"Fake limp",
"Fancy clothes",
"Fat",
"Fit",
"Freckled",
"Frizzy hair",
"Gap-toothed",
"Gassy",
"Gaunt",
"Goateed",
"Graying Hair",
"Great sense of smell",
"Harry arms",
"High cheek bones",
"Humpback",
"Knock kneed",
"Lanky",
"Large nose",
"Lazy eye",
"Long fingernails",
"Long hair",
"Long legs",
"Missing teeth",
"Mumbles",
"Muscled",
"No eyebrows",
"Notched ears",
"Noticeable birthmark",
"Noticeable scar",
"Peg leg",
"Perfectly groomed",
"Perfumed",
"Pierced ears",
"Pierced nose",
"Pigeon toed",
"Plump",
"Previously broken nose",
"Rat faced",
"Several warts",
"Shapely knees",
"Short",
"Short hair",
"Slightly green skin",
"Six fingers on left hand",
"Slack jawed",
"Sleek",
"Small ears",
"Sniffles constantly",
"Sparkly eyes",
"Square jaw",
"Stocky",
"Stout",
"Stubble",
"Swan necked",
"Sweaty",
"Tall",
"Tattooed",
"Thick eyebrows",
"Thick hair",
"Thin",
"Thin lips",
"Tiny feet",
"Turkey neck",
"Twitchy",
"Uneven shoulders",
"Unusually colored hair",
"Voluptuous",
"Weak-chinned",
"Well-toned calves",
"White streak in hair",
"Wide chin",
"Wide-eyed",
"Wild hair"
};
